apiVersion: v1
kind: Service
metadata:
  name: metallb-metrics
  namespace: metallb-system
  labels:
    app: metallb
    release: prometheus
spec:
  ports:
    - name: metrics
      port: 7472
      targetPort: monitoring
      protocol: TCP
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/name: metallb
  type: ClusterIP
