apiVersion: v2
name: loki
description: Loki log aggregation system - SingleBinary mode
type: application
version: 0.1.0
appVersion: "2.9.0"

dependencies:
  - name: loki
    version: "5.38.0"
    repository: "https://grafana.github.io/helm-charts"
