# Common values pour Loki
# Configuration partagée entre environnements
loki:
  auth_enabled: false
  limits_config:
    reject_old_samples: false
    reject_old_samples_max_age: 168h
    # retention_period: 1h
    # volume_enabled: true
# Ressources réduites pour environnement Vagrant
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

# Désactiver les fonctionnalités non essentielles
test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false
