apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-k8s-admin-binding
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: k8s-admin     # ou role-k8s-admin selon ton token
    apiGroup: rbac.authorization.k8s.io
