apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auditor-binding
  namespace: app
subjects:
  - kind: User
    name: k8s-auditor  # le rôle présent dans le token OIDC
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: auditor-role
  apiGroup: rbac.authorization.k8s.io