# kube/charts/tempo/common-values.yaml
tempo:
  metricsGenerator:
    enabled: true

  persistence:
    enabled: false

  service:
    type: ClusterIP

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
